### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by YenBenGrey** [rm2kdev/foundry-dnd-beyond-rolls-companion#1]
How do you download the companion app, and then when you have (because I thinkI have downloaded a zip file, in there are two files, a js one and a json one. What do I do with them? How do I open them with node.js?

**Comment by rm2kdev** [comment]
![image](https://user-images.githubusercontent.com/845245/208272283-68be0ac1-6084-4abe-bf7c-d011105cdd16.png)
In GitHub you can click the green code button, then select "download zip" and it will download the files into a zip folder 👍 

Once you've got the files, navigate to them with terminal either typing "cd" "space" and dragging the folder onto the terminal window, or navigating with "cd pathtofolder"

Then start it with node "node server.js" and it should say "Waiting for foundry requests: http://localhost:8745"

Hope this helps!
